// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'
import OriginAxios from 'axios'
import VueI18n from 'vue-i18n'
import VueSweetalert2 from 'vue-sweetalert2'
import VueCryptojs from 'vue-cryptojs';
import { httpClient } from './interceptor/HttpClient.js'


Vue.use(VueSweetalert2)
Vue.use(VueCryptojs)
Vue.use(require('vue-moment'));
Vue.use(router)
Vue.config.productionTip = false
Vue.use(VueI18n)
Vue.prototype.axios = httpClient
Vue.prototype.originAxios = OriginAxios

const messages = {
    "en": {
    "label.no.registered.data":"Data was not registered",
    "main.menu.home":"Home",
    "main.menu.working":"Case",
    "main.menu.history":"History",
    "main.menu.call":"Contact",
    "main.menu.more":"More",
    "main.menu.today":"Today",
    "login.label.surveyor": "Roojai.com Surveyor",
    "login.label.phone.number": "Enter your phone number",
    "login.label.send.otp": "Send OTP",
    "login.label.didnt.otp": "I didn’t receive OTP. ",
    "login.label.resent.otp": "Resend OTP",
    "login.label.verify.otp": "Verify OTP",
    "login.label.ref.code": "Ref Code",
    "login.label.otp.code": "Enter OTP Code",
    "login.label.email": " Email ",
    "login.label.phone.not.found": " Not found your phone in database ",
    "login.label.email.req.over.limit": " You have entered wrong OTP 10 times, please try after 60 ",
    "login.label.you.can.login.after.minute": " You can login again after ",
    "login.label.minute": " minute ",
    "login.label.incorrect.verify.otp": " Incorrect OTP ",
    "login.label.fails.verify.otp": "The OTP may have expired. Please request for OTP again.",
    "login.label.you.have": " you have left ",
    "login.label.times.for.wrong.otp.before.you.account.will.be.baned": " times for wrong otp before you account will be baned ",
    "history.label.report.an.accident": "Report an accident",
    "history.label.car.breakdown": "Car Breakdown",
    "history.label.caseid": "Case ID",
    "history.label.appointment.time": "Appointment",
    "history.label.end.time" : "Complete at",
    "history.label.created.time": "Created at",
    "history.label.work.directions": "Work directions.",
    "history.label.select.date": "Select completed date",
    "history.label.no.found": "No history found",
    "mainmenu.label.select.status.work": "Select Status Work",
    "mainmenu.label.active": "Active",
    "mainmenu.label.inactive": "Inactive",
    "mainmenu.label.busy": "Busy",
    "mainmenu.label.call": "Call now",
    "mainmenu.label.nocase" : 'No claim assigned, Try to Refresh !',
    "mainmenu.label.refresh" : 'Refresh',
    "mainmenu.label.do.you.want.to.call.call.center": "Do you want to call CallCenter",
    "mainmenu.label.do.you.want.to.logout": "Do you want to logout",
    "mainmenu.label.do.you.want.to.accept.case": "Do you want to accept case?",
    "mainmenu.label.car.breakdown": "Car Breakdown",
    "mainmenu.label.follow.up": "Follow-up",
    "mainmenu.label.video.survey" : "Video Survey",
    "mainmenu.label.no.type" : "No type value",
    "mainmenu.label.welcome.to.roojai.com": "Welcome to Roojai.com",
    "mainmenu.label.surveyor": "Surveyor",
    "mainmenu.label.call.center": "Contact call Center",
    "mainmenu.label.history.work": "History work",
    "mainmenu.label.logout": "Logout",
    "mainmenu.label.report.an.accident": "Report an accident",
    "mainmenu.label.caseid": "Case ID",
    "mainmenu.label.confirm": "Confirm",
    "mainmenu.label.warning": "Warning",
    "mainmenu.label.check.internet": "Please check internet",
    "mainmenu.label.check.gps": "Please check gps",
    "realtimemap.label.surveyor.in.travel": "Surveyor in travel",
    "realtimemap.label.arrive": "Arrive",
    "realtimemap.label.survey.report": "Report",
    "realtimemap.label.no.schedule": "No schedule",
    "realtimemap.label.call": "Call",
    "realtimemap.label.google.map.and.location.details": "Google map and location details",
    "realtimemap.label.customer.location": "Customer location.",
    "realtimemap.label.complete": "Complete",
    "mainmenu.label.working": "Busy",
    "mainmenu.label.change.status": "Confirm Change Status",
    "mainmenu.label.confirm.change.status": "Do you want Change Status to",
    "mainmenu.label.status.active": "Active",
    "mainmenu.label.status.in.active": "In Active",
    "mainmenu.label.ok": "OK",
    "mainmenu.label.cancel": "Cancel",
    "mainmenu.label.accept" : "ACCEPT",
    "mainmenu.label.resume" : "RESUME",
    "mainmenu.label.start" : "START",
    "mainmenu.label.policy" : "Policy",
    "mainmenu.label.confirm.to.accept.case": "Confirm to accept case",
    "mainmenu.label.do.you.want.to.accect.case": "Do you want to Accept Case",
    "mainmenu.label.km": "Km.",
    "mainmenu.label.min": "min.",
    "mainmenu.label.gps.ok": "Gps is ok.",
    "mainmenu.label.gps.not.ok": "GPS isn't ok.",
    "mainmenu.label.warning.save": "Warning save.",
    "mainmenu.label.warning.save.complete": "Save complete.",
    "mainmenu.label.warning.save.error": "Error,Can't save.",
    "mainmenu.label.header.policy.detail": "Policy Detail.",
    "mainmenu.label.do.you.need.to.exit": "Do you need to exit.",
    "mainmenu.label.update.new.version": "Please to update new version.",

    "mainmenu.label.accessory": "Car Accessories",

    "label.loss.date": "Loss date",
    "label.incident.location": "Incident Location",
    "label.incident.drivers": "Incident drivers",

    "realtimemap.label.confirm.to.working": "Confirm to Working.",
    "realtimemap.label.you.arrive": "You arrive",
    "realtimemap.label.you.complete": "This Work Complete?",
    "realtimemap.label.confirm.to.call": "Confirm to Call",
    "realtimemap.label.do.you.want.to.call": "Do you want to Call",
    "login.footer.text": "Roojai co.,ltd. 4/222 Harbormall Unit 11A01, 11th fl., Sukumvit Rd., Moo 10, T.Tungsukla, A.Sriracha, Chonburi 20230",
    "modal.accept.case" : "Confirm to Case ID",
    "modal.policy.dt.head.label.search.policy":"Search Policy number",
    "modal.policy.dt.voluntary":"Voluntary ",
    "modal.policy.dt.period":"Period",
    "modal.policy.dt.driver":"Driver plan", 
    "modal.policy.dt.fix":"Garage plan",
    "modal.policy.dt.placeholder.label.search.policy":"Search Policy number",
    "modal.policy.dt.ddl.option.type.policy.number":"Policy number",
    "modal.policy.dt.ddl.option.type.phone.number":"Phone number",
    "modal.policy.dt.ddl.option.type.car.plate":"Car plate",
    "modal.policy.dt.list.item.label.car.plate.province":"Province",
    "modal.policy.dt.list.item.label.policy.number":"Policy number",
    "modal.policy.dt.list.item.label.claim.number":"Claim number",
    "modal.policy.dt.list.item.label.car.plate":"Car plate",
    "modal.policy.dt.list.item.label.status":"Status",
    "modal.policy.dt.list.item.label.car.asset":"Brand/Model/Year",
    "modal.policy.dt.list.item.label.car.brand":"Brand",
    "modal.policy.dt.list.item.label.car.model":"Model",
    "modal.policy.dt.list.item.label.car.year":"Year",
    "modal.policy.dt.list.item.label.chassis.number":"Chassis number",
    "modal.policy.dt.list.item.label.end.date":"End date",
    "modal.policy.dt.list.item.label.start.date":"Start date",
    "modal.policy.dt.list.item.label.plan.type":"Plan Type",
    "modal.policy.dt.list.item.label.excess":"Excess",
    "modal.policy.dt.list.item.label.compulse":"Compulsory",
    "modal.policy.dt.keyword.validate.length":"Please enter keyword as least 4 character",
    "modal.policy.dt.btn.label.minimute.more":"Less Details",
    "modal.policy.dt.btn.label.more":"More Details",
    "modal.policy.dt.label.policy.holder.name":"Policy Holder name",
    "modal.policy.dt.label.policy.holder.phone":"Customer phone",
    "modal.policy.dt.label.odometer.reading":"Odometer reading",
    "modal.policy.dt.label.car.camera.installed":"Car Camera Installed",
    "modal.policy.dt.label.main.driver":"Main driver",
    "modal.policy.dt.label.other.driver":"Name driver",
    "modal.pilicy.dt.label.yes.compulse":"Yes",
    "modal.pilicy.dt.label.no.compulse":"No",
    "modal.label.no.address":"Cannot get location ",
    "modal.label.refresh.address":"try refresh !",
    "modal.label.confirm.address":"Confirm location",
    "modal.error.enter.data":"Fail",
    "modal.error.location.data":"Can not define location ",
    "modal.error.approx.time":"Can't calculate time travel/distance please check GPS and try again.",


    "surveyform.label.incident.driver" : "Incident Driver",
    "surveyform.label.ic.passport" : "IC/Passport*",
    "surveyform.button.search.account" : "Search Account",
    "surveyform.label.firstname" : "First Name*",
    "surveyform.label.lastname" : "Last Name*",
    "surveyform.label.phone" : "Mobile No.*",
    "surveyform.label.email" : "Email",
    "surveyform.label.driving.license" : "Driving License",
    "surveyform.label.driving.license.type" : "Driving License Type",
    "surveyform.label.lang" : "Contact preferred language",
    "surveyform.label.accident.detail" : "Accident details",
    "surveyform.label.cause.type" : "Cause Type",
    "surveyform.label.incident.type" : "Incident Type",
    "surveyform.label.liability" : "The insured driver is",
    "surveyform.tp.label.liability" : "The thirdparty driver is",
    "surveyform.label.investigate.remark" : "Investigate Remark",
    "surveyform.label.insured.vehicle" : "Insured Vehicle",
    "surveyform.label.is.car.drivable" : "Is car drivable ?",
    "surveyform.label.vehicle.damage" : "Vehicle Damage",
    "surveyform.label.vehicle.level" : "Damage Level",
    "surveyform.label.odometer.reading" : "Odometer reading",
    "surveyform.label.car.camera.install" : "Car camera installed ?",
    "surveyform.label.car.camera.working" : "Car camera is working ?",
    "surveyform.label.car.at.garage" : "Car is at Garage/Dealer ?",
    "surveyform.label.garage.dealer" : "Garage/Dealer",
    "surveyform.label.modal.show.damage" : "Show damage",
    "surveyform.label.modal.del.damage" : "Delete this damage",
    "surveyform.label.injury.property" : "Injury/property",
    "surveyform.label.number.passenger" : "Number of passenger",
    "surveyform.label.driver.injured" : "Is driver injured ?",
    "surveyform.label.injured.name" : "Injured name",
    "surveyform.label.injured.relation" : "Relations",
    "surveyform.label.injured.detail" : "Detail",
    "surveyform.label.deduct.excess" : "Deductible / Other Excess",
    "surveyform.label.deductible" : "Policy Deductible",
    "surveyform.label.otherexcess" : "Other excess",
    "surveyform.label.remark" : "Remark",
    "surveyform.label.fraud.section" : "Fraud Section",
    "surveyform.label.suspected" : "Suspected Fraud",
    "surveyform.label.internal.comment" : "Internal Comment",
    "surveyform.label.fraud.comment" : "Fraud Comment",
    "surveyform.label.noify.related" : "Notify Related People ?",
    "surveyform.label.preview" : "Preview Survey Report",
    "surveyform.button.add.thirdparty" : "Add Third-party",
    "surveyform.label.thirdparty.name" : "1. Third-party driver",
    "surveyform.label.thirdparty.vehicledetail" : "2. Vehicle details",
    "surveyform.label.thirdparty.make" : "Car make",
    "surveyform.label.thirdparty.model" : "Car model",
    "surveyform.label.thirdparty.carplate" : "Car plate",
    "surveyform.label.thirdparty.province" : "Car province",
    "surveyform.label.thirdparty.chassisno" : "Chassis No",
    "surveyform.label.thirdparty.insurecompany" : "Insurance company",
    "surveyform.label.thirdparty.plantype" : "Plan type",
    "surveyform.label.thirdparty.tppropdamage" : "TP property damage ?",
    "surveyform.label.thirdparty.tpinsure" : "TP insurance",
    "surveyform.label.thirdparty.tpdamagedetail" : "TP Damage detail",
    "surveyform.label.thirdparty.anyinjuerd" : "Any injury ?",
    "surveyform.label.thirdparty.injuredname" : "Injured name",
    "surveyform.label.thirdparty.injuredrelation" : "Relations",
    "surveyform.label.thirdparty.injureddetail" : "Injured Detail",
    "surveyform.label.thirdparty.iscardamage" : "Is car damage ?",
    "surveyform.label.thirdparty.preview" : "Preview Third-party Report",
    "surveyform.label.thirdparty.list" : "Third-party list",
    "surveyform.warn.sure" : "Are you sure",
    "surveyform.warn.sure.message" : "You want to delete?",
    "surveyform.save.sure.message" : "You want to save?",
    "surveyform.del.success.message" : "Delete successfully!",
    "surveyform.success" : "Success!",
    "surveyform.submit.saved" : "Your form was saved.",
    "surveyform.save.success.message" : "Data was saved successfully",
    "surveyform.warn.error" : "Error!",
    "surveyform.warn.getdata" : "Can't get data",
    "surveyform.submit.fail" : "Can't save form with message :",
    "surveyform.data.not.found" : "Data not found.",
    "surveyform.warn.error.account.search" : "Cannot get account data. Note: Please fill in the data incase new user",
    "surveyform.warn.success.account.search" : "Account found.",
    "surveyform.label.header.add.damage" : "Add damage",
    "surveyform.label.header.add.company" : "Add Insurance company",
    "surveyform.label.plan.one" : "Type 1",
    "surveyform.label.plan.two" : "Type 2",
    "surveyform.label.plan.three" : "Type 3",
    "surveyform.label.plan.twoplus" : "Type 2+",
    "surveyform.label.plan.threeplus" : "Type 3+",
    "surveyform.label.plan.compulsory" : "Compulsory Only",
    "surveyform.label.plan.no" : "No",
    "surveyform.text.notify.related" : "Click ok to send email to related peeple.",
    "surveyform.btn.next" : "NEXT",
    "surveyform.btn.prev" : "PREV",
    "surveyform.btn.preview" : "PREVIEW",
    "surveyform.pls.select" : "Please select",
    "surveyform.pls.select.causetype" : "Please select causetype",
    "surveyform.no.damage.added" : "No item added",
    "surveyform.search.select" : "Search & Select",
    "surveyform.loading.list" : "Loading...",
    "surveyform.choice.yes" : "Yes",
    "surveyform.choice.no" : "No",
    "surveyform.tp.remove" : "Remove",


    "validate.word.error" : "Error Validation",
    "validate.id.card" : "Please insert ID Card/Passport",
    "validate.damage.keyword" : "Please insert damage keyword",
    "validate.company.keyword" : "Please insert keyword at least 3 digit",
    "validate.contact.id" : "- Please insert ID/Passport",
    "validate.contact.name" : "- Please insert First name/ Last name",
    "validate.contact.phone" : "- Please insert mobile number",

    "file.upload.label" : "UPLOADPHOTO",
    "file.upload.header" : "Photos",
    "file.upload.empty" : "Please upload file",
    "file.upload.take.photo" : "Camera",
    "file.upload.add.photo" : "Add file",
    "file.upload.confirm.del" : "OK",
    "file.upload.cancel.del" : "Cancel",
    "file.upload.del.file.photo" : "Delete confirmation",
    "file.upload.del.warning" : "Are you sure to delete ?",
    "file.upload.err.add" : "Cannot get file data. Please try again later",
    "file.upload.warn.token.expire": "Cannot proceed token expired", 

    "workshop.contact" : "Contact",
    "workshop.roojai" : "Roojai.com",
    "workshop.please.input.claim" : "Please input your claim number and tap 'Video call' to contact Roojai.com",
    "workshop.start.call" : "Video call",
    "workshop.page" : "Garage Video Call",
    "workshop.warn.failed" : "Failed",
    "workshop.warn.claim.not.fund" : "Sorry we couldn't found your claim number. If you need helps please contact 02-582-8899",

    "label.please.wait.processing": "Processing",
    "label.more.profile":"Profile",
    "label.more.tel":"Tel. : ",
    "label.more.email":"Email : ",
    "label.more.lang":"Language",

    "working.label.nocase" : 'No in handle case',
    "scene.add" : "Add",
    "scene.select" : "Select Scenario",
    "claim.scenarios": "Claim scenario",
    "no.scenario.selected" : "No scenario selected",
    "sceneActive.no.select" : "Please select scenario",
    "claim.s1":"Vehicle 1 turning out from a side road hit with Vehicle 2 approaching main road",
    "claim.s2":"Vehicle 1 making a u-turn at an intersection hit with Vehicle 2 moving straight ahead",
    "claim.s3":"Vehicle 1 trying to turn into the side road hit with Vehicle 2 moving into the side road",
    "claim.s4":"Vehicle 1 moving straight across junction hit with Vehicle 2 moving straight from the right direction",
    "claim.s5":"Vehicle 1 trying to turn right hit with Vehicle 2 moving straight across junction",
    "claim.s6":"Vehicle 1 turning right from opposite direction hit with vehicle 2 turning left",
    "claim.s7":"Vehicle 1 turning left into main road at intersection hit with vehicle 2 moving straight ahead ",
    "claim.s8":"Vehicle 1 turning right from opposite direction into main road hit with vehicle 2 moving straight ahead",
    "claim.s9":"Vehicle 1 turning right  into main road hit with vehicle 2 moving straight ahead",
    "claim.s10":"Vehicle 1 turning left into main road hit with vehicle 2 moving straight ahead",
    "claim.s11":"Vehicle 1 making a u-turn across main road hit with Vehicle 2 moving straight ahead",
    "claim.s12":"Vehicle 1 entering into the roundabout hit with Vehicle 2 moving along in the roundabount",
    "claim.s13":"Vehicle 1 changing lane while moving into the roundabout hit with Vehicle 2 moving along",
    "claim.s14":"Vehicle 1 changing lane hit with Vehicle 2 moving in own lane",
    "claim.s15":"Vehicle 1 encroaching/straddling lanes hit with Vehicle 2 moving in own lane",
    "claim.s16":"Vehicle 1 converging into single lane hit with Vehicle 2 converging into a single lane",
    "claim.s17":"Vehicle 1 hit with Vehicle 2 when both vehicles changing lane",
    "claim.s18":"Vehicle 1 hit with Vehicle 2 when crosses a centre line and sideswipes",
    "claim.s19":"Vehicle 1 losing control and encroaching into patch of Vehicle 2",
    "claim.s20":"Vehicle 1 moving/reversing then hit Vehicle 2 parking",
    "claim.s21":"Vehicle 1 moving/reversing into parking lot then hit Vehicle 2 parking",
    "claim.s22":"Vehicle 1 moving/reversing out of parking lot then hit Vehicle 2 going straight",
    "claim.s23":"Vehicle 1 hit with Vehicle 2 when both moving/reversing out of parking lot ",
    "claim.s24":"Driver/passenger's Vehicle 1 open door into patch of other traffic",
    "claim.s25":"Vehicle 1 hit Vehicle 2 at  rear-end",
    "claim.s26":"Multiple vehicle rear-end collision",
    "claim.s27":"Vehicle 1 turning right at an intersection then hit with Vehicle 2 turning right",
    "claim.s28":"Vehicle 1 hit with Vehicle 2 when both vehicles turning right in the same direction",
    "claim.s29":"Vehicle 1 turning left to entering into main road hit with Vehicle 2 moving straight ahead",
    "claim.s30":"Vehicle 1 hit with Vehicle 2 when both moving and turning up/down slope",
    "claim.s31":"Vehicle 1 hit with bicycle",
    "claim.s32":"Vehicle 1 hit the pedestrians",
    "claim.s33":"Vehicle 1 turning out of the road",
    "claim.s34":"Vehicle 1 hit the barrier/bridge",
    "claim.s35":"Vehicle 1 hit with the tree",
    "claim.s36":"Vehicle 1 damage from flood",
    "claim.s37":"Vehicle 1 damage from fire",
    "claim.s38":"Vehicle 1 was stolen"
  },
  "th": {
    "label.no.registered.data":"ไม่ได้บันทึกข้อมูลไว้",
    "main.menu.home":"โฮม",
    "main.menu.working":"นัดหมาย",
    "main.menu.history":"ประวัติ",
    "main.menu.call":"ติดต่อ",
    "main.menu.more":"อื่นๆ",
    "main.menu.today":"วันนี้",
    "login.label.surveyor": "เจ้าหน้าที่สำรวจภัย Roojai.com",
    "login.label.phone.number": "กรุณากรอกหมายเลขโทรศัพท์มือถือ",
    "login.label.send.otp": "ส่งรหัสเพื่อใช้เข้าสู่ระบบ ",
    "login.label.didnt.otp": "ยังไม่ได้รับรหัส ",
    "login.label.resent.otp": "ส่งใหม่อีกครั้ง",
    "login.label.verify.otp": "ยืนยันรหัส ",
    "login.label.otp.code": "กรุณากรอก รหัสเข้าสู่ระบบ ",
    "login.label.ref.code": " เลขอ้างอิง ",
    "login.label.email": " อีเมลล์ ",
    "mainmenu.label.header.policy.detail": "รายละเอียดกรมธรรม์",
    "login.label.phone.not.found": " ไม่พบข้อมูลเบอร์โทรนี้ในระบบ ",
    "login.label.email.req.over.limit": " คุณส่งรหัส OTP ยืนยันผิดเกิน 10 ครั้ง โปรดเข้าสู่ระบบอีกครั้งหลังจาก 60 ",
    "login.label.you.can.login.after.minute": " คุณจะสามารถเข้าสู่ระบบได้อีกครั้งหลังจาก ",
    "login.label.minute": " นาที ",
    "login.label.incorrect.verify.otp": " รหัส OTP ไม่ถูกต้อง ",
    "login.label.fails.verify.otp": "รหัส OTP หมดอายุ กรุณารอรับรหัส OTP อีกครั้ง",
    "login.label.you.have": " คุณสามารถส่งรหัสได้อีก ",
    "login.label.times.for.wrong.otp.before.you.account.will.be.baned": " ครั้งสำหรับการยืนยันรหัส OTP ",
    "modal.accept.case" : "ยืนยันรับงานเหตุการณ์ ",
    "modal.policy.dt.voluntary":"กรมธรรม์ประเภท ",
    "modal.policy.dt.period":"ระยะเวลาคุ้มครอง",
    "modal.policy.dt.driver":"แผนผู้ขับขี่",
    "modal.policy.dt.fix":"แผนการซ่อม",
    "modal.policy.dt.head.label.search.policy":"ค้นหาเลขกรมธรรม์",
    "modal.policy.dt.placeholder.label.search.policy":"ค้นหาเลขกรมธรรม์",
    "modal.policy.dt.ddl.option.type.policy.number":"เลขกรมธรรม์",
    "modal.policy.dt.ddl.option.type.phone.number":"เบอร์โทร",
    "modal.policy.dt.ddl.option.type.car.plate":"ทะเบียน",
    "modal.policy.dt.list.item.label.policy.number":"เลขกรมธรรม์",
    "modal.policy.dt.list.item.label.claim.number":"เลขเคลม",
    "modal.policy.dt.list.item.label.car.plate":"ทะเบียน",
    "modal.policy.dt.list.item.label.car.plate.province":"จังหวัด",
    "modal.policy.dt.list.item.label.status":"สถานะ",
    "modal.policy.dt.list.item.label.car.asset":"ยี่ห้อ/รุ่น/ปี",
    "modal.policy.dt.list.item.label.car.brand":"ยี่ห้อ",
    "modal.policy.dt.list.item.label.car.model":"รุ่น",
    "modal.policy.dt.list.item.label.car.year":"ปี",
    "modal.policy.dt.list.item.label.chassis.number":"เลขคัสซี",
    "modal.policy.dt.list.item.label.end.date":"วันหมดอายุ",
    "modal.policy.dt.list.item.label.start.date":"วันที่เริ่มต้น",
    "modal.policy.dt.list.item.label.plan.type":"ประเภทการคุ้มครอง",
    "modal.policy.dt.list.item.label.excess":"ค่าเสียหายส่วนเกิน",
    "modal.policy.dt.list.item.label.compulse":"พรบ.",
    "modal.policy.dt.keyword.validate.length":"กรุณากรอกคำค้นหาอย่างน้อย 4 ตัวอักษร",
    "modal.policy.dt.btn.label.more":"รายละเอียดเพิ่มเติม",
    "modal.policy.dt.btn.label.minimute.more":"ย่อรายละเอียดเพิ่มเติม",
    "modal.policy.dt.label.policy.holder.name":"ผู้เอาประกันภัยชื่อ",
    "modal.policy.dt.label.policy.holder.phone":"เบอร์ติดต่อลูกค้า",
    "modal.policy.dt.label.odometer.reading":"เลขไมล์",
    "modal.policy.dt.label.car.camera.installed":"ติดตั้งกล้อง",
    "modal.policy.dt.label.main.driver":"ผู้ขับขี่หลัก",
    "modal.policy.dt.label.other.driver":"ผู้ชับชีขี่รอง",
    "modal.pilicy.dt.label.yes.compulse":"รวม",
    "modal.pilicy.dt.label.no.compulse":"ไม่รวม",
    "modal.label.no.address":"ไม่พบข้อมูลสถานที่",
    "modal.label.refresh.address":"รีเฟรชอีกครั้ง !",
    "modal.label.confirm.address":"ยืนยันสถานที่",
    "modal.error.enter.data":"ผิดพลาด",
    "modal.error.location.data":"ไม่สามารถระบุสภานที่ได้ ",
    "modal.error.approx.time":"ไม่สามารถระบุ ระยะทาง/ระยะเวลา ในการเดินทางได้ กรุณารีเฟรช GPS และลองอีกครั้ง",

    "history.label.report.an.accident": "แจ้งอุบัติเหตุ",
    "history.label.car.breakdown": "รถเสีย",
    "history.label.caseid": "หมายเลขเหตุการณ์",
    "history.label.appointment.time": "วัน-เวลานัดหมาย",
    "history.label.end.time": "วัน-เวลาสิ้นสุดเหตุการณ์",
    "history.label.created.time": "วัน-เวลาที่สร้างเหตุการณ์",
    "history.label.work.directions": "เส้นทางการปฏิบัติงาน",
    "history.label.select.date": "เลือกวันที่งานเสร็จ",
    "history.label.no.found": "ไม่พบประวัติการทำงาน",
    "mainmenu.label.select.status.work": "สถานะการทำงาน",
    "mainmenu.label.active": "พร้อมปฏิบัติงาน",
    "mainmenu.label.inactive": "ไม่พร้อมปฏิบัติงาน",
    "mainmenu.label.busy": "กำลังปฏิบัติงาน",
    "mainmenu.label.call": "โทรตอนนี้",
    "mainmenu.label.nocase" : 'ไม่มีงานที่ได้รับมอบหมาย ลองรีเฟรช!',
    "mainmenu.label.refresh" : 'รีเฟรช',
    "mainmenu.label.do.you.want.to.call.call.center": "คุณต้องการโทรหาฝ่ายบริการลูกค้าไหม",
    "mainmenu.label.do.you.want.to.logout": "คุณต้องการออกจากระบบไหม",
    "mainmenu.label.do.you.want.to.accept.case": "คุณต้องการรับเหตุการณ์นี้ไว้ไหม",
    "mainmenu.label.car.breakdown": "รถเสีย",
    "mainmenu.label.follow.up": "ติดตามงาน",
    "mainmenu.label.video.survey" : "วิดีโอเซอร์เวย์",
    "mainmenu.label.no.type" : "ไม่มีประเภทของเหตุการณ์",
    "mainmenu.label.welcome.to.roojai.com": "ขอต้อนรับสู่ Roojai.com",
    "mainmenu.label.surveyor": "เจ้าหน้าที่สำรวจภัย",
    "mainmenu.label.call.center": "ฝ่ายบริการลูกค้า",
    "mainmenu.label.history.work": "ประวัติการทำงาน",
    "mainmenu.label.logout": "ออกจากระบบ",
    "mainmenu.label.report.an.accident": "แจ้งอุบัติเหตุ",
    "mainmenu.label.caseid": "หมายเลขเหตุการณ์",
    "mainmenu.label.confirm": "ยืนยัน",
    "mainmenu.label.warning": "แจ้งเตือน",
    "mainmenu.label.check.internet": "กรุณาเช็คสัญญาณอินเตอร์เน็ต",
    "mainmenu.label.check.gps": "กรุณาเช็คสัญญาณจีพีเอส",
    "realtimemap.label.surveyor.in.travel": "เจ้าหน้าที่กำลังเดินทาง",
    "surveyform.label.driving.license" : "หมายเลขใบขับขี่",
    "surveyform.label.driving.license.type" : "ประเภทใบขับขี่",
    "realtimemap.label.arrive": "มาถึงแล้ว",
    "realtimemap.label.survey.report": "รายงาน",
    "realtimemap.label.no.schedule": "ไม่มีการนัดหมาย",
    "realtimemap.label.call": "โทร",
    "realtimemap.label.google.map.and.location.details": "Google map และรายละเอียดสถานที่",
    "realtimemap.label.customer.location": "ตำแหน่งลูกค้า",
    "realtimemap.label.complete": "จบงาน",
    "mainmenu.label.working": "งานปัจจุบัน",
    "mainmenu.label.change.status": "ยืนยันการเปลี่ยนสถานะ",
    "mainmenu.label.confirm.change.status": "คุณต้องการเปลี่ยนสถานะเป็นสถานะ",
    "mainmenu.label.status.active": "พร้อมปฏิบัติงาน",
    "mainmenu.label.status.in.active": "ไม่พร้อมปฏิบัติงาน",
    "mainmenu.label.ok": "ตกลง",
    "mainmenu.label.cancel": "ยกเลิก",
    "mainmenu.label.accept" : "รับงาน",
    "mainmenu.label.resume" : "ดำเนินการต่อ",
    "mainmenu.label.start" : "เริ่มงาน",
    "mainmenu.label.policy" : "กรมธรรม์",
    "mainmenu.label.confirm.to.accept.case": "ยืนยันการรับงาน",
    "surveyform.label.number.passenger" : "จำนวนผู้โดยสาร",
    "mainmenu.label.do.you.want.to.accect.case": "คุณต้องการรับงานนี้หรือไม่",
    "mainmenu.label.km": "กม.",
    "mainmenu.label.min": "นาที.",
    "mainmenu.label.gps.ok": "พบสัญญาณจีพีเอส.",
    "mainmenu.label.gps.not.ok": "ไม่พบสัญญาณจีพีเอส.",
    "mainmenu.label.warning.save": "สถานะการบันทึก.",
    "mainmenu.label.warning.save.complete": "บันทึกสำเร็จ.",
    "mainmenu.label.warning.save.error": "ไม่สามารถบันทึกข้อมูลได้",
    "mainmenu.label.do.you.need.to.exit": "คุณต้องการออกจากโปรแกรมหรือไม่",
    "mainmenu.label.update.new.version": "กดเพื่ออัปเดทแอปพลิเคชั่นเวอร์ชั่นล่าสุด",


    "mainmenu.label.accessory": "อุปกรณ์เพิ่มเติม",

    "label.loss.date": "วันที่เกิดเหตุ",
    "label.incident.location": "สถานที่เกิดเหตุ",
    "label.incident.drivers": "ผู้ขับขี่ขณะเกิดเหตุ",


    "realtimemap.label.confirm.to.working": "ยืนยันการปฏิบัติงาน",
    "realtimemap.label.you.arrive": "คุณมาถึงที่เกิดเหตุแล้ว",
    "realtimemap.label.confirm.to.call": "ยืนยันการโทร",
    "realtimemap.label.do.you.want.to.call": "คุณต้องการโทรหรือไม่",
    "realtimemap.label.you.complete": "การปฏิบัติงานเสร็จสิ้นแล้ว",
    "login.footer.text": "บริษัท รู้ใจ จำกัด, 4/222 อาคารฮาร์เบอร์ มอลล์ ชั้นที่ 11 ห้อง 11A01 หมู่ที่ 10 ถนนสุขุมวิท ตำบลทุ่งสุขลา อำเภอศรีราชา จังหวัดชลบุรี 20230",

    "surveyform.label.incident.driver" : "ข้อมูลผู้ขับขี่",
    "surveyform.label.ic.passport" : "บัตรปชช./หนังสือเดินทาง*",
    "surveyform.button.search.account" : "ค้นหาบัญชีรู้ใจ",
    "surveyform.label.firstname" : "ชื่อ*",
    "surveyform.label.lastname" : "นามสกุล*",
    "surveyform.label.phone" : "เบอร์โทร*",
    "surveyform.label.email" : "อีเมล",
    "surveyform.label.lang" : "ภาษาสำหรับติดต่อ",
    "surveyform.label.accident.detail" : "ข้อมูลอุบัติเหตุ",
    "surveyform.label.cause.type" : "ประเภทเหตุ",
    "surveyform.label.incident.type" : "ลักษณะเหตุ",
    "surveyform.label.liability" : "รถประกันเป็นฝ่าย",
    "surveyform.tp.label.liability" : "รถคู่กรณีเป็นฝ่าย",
    "surveyform.label.investigate.remark" : "รายละเอียดการเกิดอุบัติเหตุ",
    "surveyform.label.insured.vehicle" : "ข้อมูลยานพาหนะ",
    "surveyform.label.is.car.drivable" : "รถยนต์สามารถขับขี่ ?",
    "surveyform.label.vehicle.damage" : "ความเสียหาย",
    "surveyform.label.vehicle.level" : "ระดับ",
    "surveyform.label.odometer.reading" : "เลขไมล์",
    "surveyform.label.car.camera.install" : "ติดตั้งกล้องรถยนต์ ?",
    "surveyform.label.car.camera.working" : "กล้องทำงานปกติ ?",
    "surveyform.label.car.at.garage" : "รถยนต์อยู่ที่อู่ / ศูนย์ ?",
    "surveyform.label.garage.dealer" : "ชื่ออู่ / ศูนย์",
    "surveyform.label.modal.show.damage" : "แสดงรายการความเสียหาย",
    "surveyform.label.modal.del.damage" : "ลบรายการนี้",
    "surveyform.label.injury.property" : "การบาดเจ็บ/ทรัพย์สิน",
    "surveyform.label.driver.injured" : "ผู้ขับขี่บาดเจ็บ ?",
    "surveyform.label.injured.name" : "ชื่อคนเจ็บ",
    "surveyform.label.injured.relation" : "ความสัมพันธ์",
    "surveyform.label.injured.detail" : "อาการบาดเจ็บ",
    "surveyform.label.deduct.excess" : "ความรับผิดส่วนแรก / ค่าเสียหายกรณีผิดเงื่อนไข",
    "surveyform.label.deductible" : "ความรับผิดส่วนแรก",
    "surveyform.label.otherexcess" : "ค่าเสียหายกรณีผิดเงื่อนไข",
    "surveyform.label.remark" : "หมายเหตุ",
    "surveyform.label.fraud.section" : "การฉ้อโกง",
    "surveyform.label.suspected" : "สงสัยว่ามีการฉ้อโกง",
    "surveyform.label.internal.comment" : "ความคิดเห็นภายใน",
    "surveyform.label.fraud.comment" : "ความคิดเห็นการฉ้อโกง",
    "surveyform.label.noify.related" : "ส่งรายงานให้ผู้เกี่ยวข้องทันที ?",
    "surveyform.label.preview" : "แสดงรายงานอุบัติเหตุ",
    "surveyform.button.add.thirdparty" : "เพิ่มคู่กรณี",
    "surveyform.label.thirdparty.name" : "1. ข้อมูลผู้ขับขี่คู่กรณี",
    "surveyform.label.thirdparty.vehicledetail" : "2. ข้อมูลยานพาหนะ",
    "surveyform.label.thirdparty.make" : "ยี่ห้อรถยนต์",
    "surveyform.label.thirdparty.model" : "รุ่นรถยนต์",
    "surveyform.label.thirdparty.carplate" : "ทะเบียนรถ",
    "surveyform.label.thirdparty.province" : "จังหวัด",
    "surveyform.label.thirdparty.chassisno" : "เลขตัวถัง",
    "surveyform.label.thirdparty.insurecompany" : "บริษัทประกัน",
    "surveyform.label.thirdparty.plantype" : "ความคุ้มครอง",
    "surveyform.label.thirdparty.tppropdamage" : "ทรัพย์สินเสียหาย ?",
    "surveyform.label.thirdparty.tpinsure" : "บริษัทประกันภัย",
    "surveyform.label.thirdparty.tpdamagedetail" : "รายการความเสียหาย",
    "surveyform.label.thirdparty.anyinjuerd" : "มีคนเจ็บ ?",
    "surveyform.label.thirdparty.injuredname" : "ชื่อคนเจ็บ",
    "surveyform.label.thirdparty.injuredrelation" : "ความสัมพันธ์",
    "surveyform.label.thirdparty.injureddetail" : "อาการบาดเจ็บ",
    "surveyform.label.thirdparty.iscardamage" : "รถยนต์เสียหาย ?",
    "surveyform.label.thirdparty.preview" : "แสดงรายงานคู่กรณี",
    "surveyform.label.thirdparty.list" : "รายชื่อคู่กรณี",
    "surveyform.warn.sure" : "แน่ใจหรือไม่",
    "surveyform.warn.sure.message" : "กรุณายืนยันการลบข้อมูล",
    "surveyform.save.sure.message" : "กรุณายืนยันการบันทึกข้อมูล",
    "surveyform.del.success.message" : "ลบข้อมูลสำเร็จ!",
    "surveyform.success" : "สำเร็จ!",
    "surveyform.submit.saved" : "แบบฟอร์มของคุณถูกบันทึกแล้ว",
    "surveyform.save.success.message" : "การบันทึกข้อมูลสำเร็จ",
    "surveyform.warn.error" : "ผิดพลาด!",
    "surveyform.warn.getdata" : "ไม่สามารถรับข้อมูลได้",
    "surveyform.submit.fail" : "ข้อความจากระบบ :",
    "surveyform.data.not.found" : "ไม่พบข้อมูล",
    "surveyform.warn.error.account.search" : "ไม่พบข้อมูลบัญชีรู้ใจ หมายเหตุ: ในกรณีเป็นผู้ใช้ใหม่กรุณากรอกข้อมูลเพื่อทำการสร้างบัญชีรู้ใจ",
    "surveyform.warn.success.account.search" : "พบข้อมูลบัญชีรู้ใจ",
    "surveyform.label.header.add.damage" : "เพิ่มรายการความเสียหาย",
    "surveyform.label.header.add.company" : "เพิ่มบริษัทประกันภัย",
    "surveyform.label.plan.one" : "ประเภท 1",
    "surveyform.label.plan.two" : "ประเภท 2",
    "surveyform.label.plan.three" : "ประเภท 3",
    "surveyform.label.plan.twoplus" : "ประเภท 2+",
    "surveyform.label.plan.threeplus" : "ประเภท 3+",
    "surveyform.label.plan.compulsory" : "พรบ.",
    "surveyform.label.plan.no" : "ไม่มีประกัน",
    "surveyform.text.notify.related" : 'คลิก OK เพื่อส่งอีเมลให้ผู้ที่เกี่ยวข้อง',
    "surveyform.btn.next" : "ต่อไป",
    "surveyform.btn.prev" : "ก่อนหน้า",
    "surveyform.btn.preview" : "ดูตัวอย่าง",
    "surveyform.pls.select" : "กรุณาเลือก",
    "surveyform.pls.select.causetype" : "กรุณาเลือกประเภทเหตุก่อน",
    "surveyform.no.damage.added" : "ไม่มีรายการที่เพิ่ม",
    "surveyform.search.select" : "ค้นหาและเลือก",
    "surveyform.loading.list" : "กำลังโหลด...",
    "surveyform.choice.yes" : "ใช่",
    "surveyform.choice.no" : "ไม่",
    "surveyform.tp.remove" : "ลบ",

    "validate.word.error" : "การตรวจสอบข้อมูลผิดพลาด",
    "validate.id.card" : "กรุณากรอกเลขบัตรประชาชน หรือ พาสปอร์ต",
    "validate.damage.keyword" : "กรุณากรอกคำสำหรับค้นรายการความเสียหาย",
    "validate.company.keyword" : "กรุณากรอกคำค้นหาอย่างน้อย 3 ตัวอักษร",
    "validate.contact.id" : "- กรุณาระบุบัตรประชาชน/เลขพาสปอร์ต",
    "validate.contact.name" : "- กรุณาระบุชื่อ-นามสกุล",
    "validate.contact.phone" : "- กรุณาระบุเบอร์โทรศัพท์",

    "file.upload.label" : "อัพโหลดรูป",
    "file.upload.header" : "รูปภาพ",
    "file.upload.empty" : "กรุณาอัพโหลดไฟล์",
    "file.upload.take.photo" : "ถ่ายรูป",
    "file.upload.add.photo" : "เพิ่มไฟล์",
    "file.upload.confirm.del" : "ยืนยัน",
    "file.upload.cancel.del" : "ยกเลิก",
    "file.upload.del.file.photo" : "ยืนยันการลบไฟล์",
    "file.upload.del.warning" : "แน่ใจหรือว่าต้องการลบไฟล์ ?",
    "file.upload.err.add" : "ไม่สามารถดึงข้อมูลไฟล์ได้ กรุณาลองอีกครั้งภาพหลัง",
    "file.upload.warn.token.expire": "ไม่สามารถดำเนินการได้เนื่องจากโทเคนหมดอายุ", 

    "workshop.contact" : "ติดต่อ",
    "workshop.roojai" : "รู้ใจ",
    "workshop.please.input.claim" : "กรุณากรอกหมายเลขเคลม และกด 'วิดีโอคอล' เพื่อ ติดต่อกับทีมงานรู้ใจ",
    "workshop.start.call" : "วีดีโอคอล",
    "workshop.page" : "สำหรับอู่ซ่อมรถ",
    "workshop.warn.failed" : "ผิดพลาด",
    "workshop.warn.claim.not.fund" : "ขออภัยเราไม่สามารถค้นหาเลขเคลมนี้ได้ หากต้องการความช่วยเหลือกรุณาติดต่อ 02-582-8899",

    "label.please.wait.processing":"กำลังโหลด",
    "label.more.profile":"โปรไฟล์",
    "label.more.tel":"โทร. : ",
    "label.more.email":"อีเมล : ",
    "label.more.lang":"ภาษา",

    "working.label.nocase" : 'ไม่มีงานที่กำลังทำ',
    "scene.add" : "เพิ่ม",
    "scene.select" : "เลือกลักษณะเหตุการณ์",
    "no.scenario.selected" : "ไม่มีลักษณะเหตุการณ์ที่เลือก",
    "claim.scenarios": "ลักษณะเหตุการณ์",
    "sceneActive.no.select" : "กรุณาเลือกเหตุการณ์",
    "claim.s1":"รถคันที่ 1 ขับเลี้ยวออกจากทางโทชนกับรถคันที่ 2 ทางตรง",
    "claim.s2":"รถคันที่ 1 ขับเลี้ยวขวาเพื่อจะเข้าซอยไม่ทันระวังรถที่วิ่งมาทางตรง",
    "claim.s3":"รถคันที่ 1 ขับเลี้ยวออกจากทางหลัก",
    "claim.s4":"รถคันที่ 1 กำลังเข้าสี่แยกชนกับรถคันที่ 2 ที่กำลังผ่านสี่แยก",
    "claim.s5":"รถคันที่ 1 เลี้ยวขวาข้ามสี่แยกชนกับรถคันที่ 2 ทางตรง",
    "claim.s6":"รถคันที่ 1 เลี้ยวขวาชนกับรถคันที่ 2 กำลังเลี้ยวซ้ายตรงทางแยก",
    "claim.s7":"รถคันที่ 1 เลี้ยวซ้ายบริเวณสี่แยกชนกับรถคันที่ 2 ทางตรง",
    "claim.s8":"รถคันที่ 1 เลี้ยวขวาบริเวณสี่แยกชนกับรถคันที่ 2 ทางตรง",
    "claim.s9":"รถคันที่ 1 ทางโทเลี้ยวขวาชนกับรถคันที่ 2 ทางตรง",
    "claim.s10":"รถคันที่ 1 ทางโทเลี้ยวซ้ายชนกับรถคันที่ 2 ทางตรง",
    "claim.s11":"รถคันที่ 1 ทางโทเลี้ยวกลับรถ ชนกับรถคันที่ 2 ทางตรง",
    "claim.s12":"รถคันที่ 1 เข้าวงเวียนชนกับรถคันที่ 2 ในวงเวียน",
    "claim.s13":"รถคันที่ 1 เปลี่ยนช่องในวงเวียนชนกับรถคันที่ 2 ",
    "claim.s14":"รถคันที่ 1 เปลี่ยนช่องทางกระทันหันชนกับรถคันที่ 2",
    "claim.s15":"รถคันที่ 1 คร่อม/ล้ำช่องทางเดินรถชนกับรถคันที่ 2 สวนทาง",
    "claim.s16":"รถคันที่ 1 เบียดกับรถคันที่ 2 ขณะเข้าช่องทางแคบ",
    "claim.s17":"รถคันที่ 1 ชนกับรถคันที่ 2 ขณะเปลี่ยนช่องทางบริเวณเส้นแบ่งช่องทางเดินรถ",
    "claim.s18":"รถคันที่ 1 เบียดกับรถคันที่ 2 บริเวณเส้นแบ่งช่องทางเดินรถ",
    "claim.s19":"รถคันที่ 1 เสียการควบคุม ล้ำข้ามมาชนในช่องทางของรถคันที่ 2 ",
    "claim.s20":"รถคันที่ 1 เสียหลักหมุนขวางถนนทำให้เฉี่ยวชนกับ รถคันที่ 2 ที่วิ่งสวนทางกัน",
    "claim.s21":"รถคันที่ 1 ชนท้ายรถยนต์ที่จอดอยู่ข้างหน้า",
    "claim.s22":"รถคันที่ 1 ขับออกหรือถอยออกจากช่องจอดรถไม่ทันระวังรถที่กำลังวิ่งมาทางตรง",
    "claim.s23":"รถคันที่ 1 ขับออกจากที่จอดรถ ชนกับรถยนต์ที่กำลังขับออกจากที่จอดฝั่งตรงข้าม",
    "claim.s24":"รถคันที่ 1 เปิดประตูไม่ทันระวัง ทำให้รถคันที่ 2 ที่วิ่งมาเฉี่ยวชนประตู",
    "claim.s25":"รถคันที่ 1 ชนท้าย รถคันที่ 2 ที่ขับอยู่ข้างหน้า",
    "claim.s26":"รถยนต์ชนกันต่อเนืองหลายคัน",
    "claim.s27":"รถคันที่ 1 เลี้ยวขวาเบียดกับ รถคันที่ 2 เลี้ยวขวาที่มาจากฝั่งตรงข้าม",
    "claim.s28":"รถคันที่ 1 เลี้ยวขวาล้ำช่องทางเบียดกับ รถคันที่ 2 ที่กำลังเลี้ยวขวาตรงสี่แยก",
    "claim.s29":"รถคันที่ 1 เลี้ยวซ้ายออกจากทางโทตัดหน้ารถยนต์ที่มาทางตรง",
    "claim.s30":"รถคันที่ 1 เฉี่ยวชนกับรถคันที่ 2 ขณะขึ้น-ลงลานจอดรถ",
    "claim.s31":"รถประกันชนรถจักรยาน",
    "claim.s32":"รถประกันชนคนเดินถนน",
    "claim.s33":"รถประกันตกข้างทาง",
    "claim.s34":"รถประกันชนเครื่องกั้น/ราวสะพาน",
    "claim.s35":"รถประกันชนต้นไม้",
    "claim.s36":"รถประกันเสียหายจากน้ำท่วม",
    "claim.s37":"รถประกันเสียหายจากไฟไหม้",
    "claim.s38":"รถประกันถูกโจรกรรม"


  }
};
// Create VueI18n instance with options
const i18n = new VueI18n({
    locale: 'th',
    fallbackLocale: 'th',
    messages,
    silentTranslationWarn: true
});

/* eslint-disable no-new */
new Vue({
    el: '#app',
    router,
    i18n,
    components: { App },
    template: '<App/>'
});
